### ISSUE TITLE
PlatformIO only has 0.1.0 but not the newer releases

### ISSUE THREAD

**Issue by marcelstoer** [Sensirion/arduino-i2c-scd4x#1]
https://platformio.org/lib/show/11777/Sensirion%20I2C%20SCD4x/installation lists only the 0.1.0 release.

I was getting the example sketch from GitHub but had the PlatformIO driver dependency pulled in when I noticed the inconsistency. 

```
lib_deps =
  https://github.com/Sensirion/arduino-i2c-scd4x#0.3.0
```
in `platformio.ini` fixes this.

Side note: `library.properties` is currently at 0.2.0.

**Comment by MBjoern** [comment]
Thank you for reporting this. We'll look into it. As you've found a suitable workaround, we'll close this issue for now. Feel free to reopen or open another one if this is not satisfying or if you encounter any other issues.

Thank you for using Sensirion sensors and our libraries.
