### ISSUE TITLE
temperature and humidity conversion not exact

### ISSUE THREAD

**Issue by fishingpole** [Sensirion/arduino-i2c-scd4x#17]
File SensirionI2CScd4x.cpp, function readMeasurement() uses 65536.0 in the conversion formulas from temperature ticks to temperature degrees C and for humidity ticks to humidity RH.

The SCD4x Datasheet Table 11 in section 3.5.2 says to use "2^16 - 1" which would be 65535.0.

**Comment by psachs** [comment]
thank you for reporting. The issue is fixed in master
