### ISSUE TITLE
Comments don't match function

### ISSUE THREAD

**Issue by echener** [Sensirion/arduino-i2c-scd4x#21]
Hello everyone,
Just wanted to point out something minor.
In the [SensirionI2CScd4x.h](https://github.com/Sensirion/arduino-i2c-scd4x/blob/master/src/SensirionI2CScd4x.h) file from line 265 to 313 the comment describing the function doesn't match the function.

I'm not sure if I should do a pull request, because it's  #stated that the file should not be changed manually.

**Comment by LeonieFierz** [comment]
Hi @echener 
Thank you for pointing this out.
We do maintain the code on our internal GitLab, so I did update it there and it is synced to the master on github.
