### ISSUE TITLE
Received NACK on transmit of address

### ISSUE THREAD

**Issue by AndreasLichtsinn** [Sensirion/arduino-i2c-scd4x#23]
I was trying exampleUsage for Arduino, but with no success: 
![image](https://user-images.githubusercontent.com/17704004/219428171-68f8c8c6-40ae-44a4-903d-da12e5de6b0e.png)

It's a Pimoroni SCD41, connected via StemmaQT/Qwiic connector to Adafruit QT-Py ESP32 S2.
I had this working before with Adafruit WipperSnapper, but since my Wi-Fi is unstable I'm looking for a standalone solution.

**Comment by qfisch** [comment]
Hello Andreas,

Unfortunately we do not have you hardware around for testing. But my best guess is the following.
Wire.h is not configured properly by default for your board. The library (by arduino) probably doesn't know the port number to use for I2C. Hence the failing communication with the sensor. 

If you find an example script for your board that establish an I2C connection using Wire.h, you can reuse the configuration in the exampleUsage here.

I hope it helps,
Let us know if we can support you further.

**Comment by AndreasLichtsinn** [comment]
Ok makes sense, the Stemma port is a secondary I2C port, I will try this route, thanks.

**Comment by AndreasLichtsinn** [comment]
![image](https://user-images.githubusercontent.com/17704004/219706584-57b1e5d5-3448-44d5-97c5-69c93c11c285.png)
Perfect, added Wire.setPins(SDA1, SCL1), very nice.
