### ISSUE TITLE
Unable to read CO2 but temperature and humidty works fine

### ISSUE THREAD

**Issue by antonio-emilio** [Sensirion/arduino-i2c-scd4x#28]
Hi everyone!
I've bougth a SCD41 sensor from mouser and developed my own custom board with it. I originally had connected 3V3 on it, but since the readings of the CO2 didn't work, I changed to 5V, but still doesn't work.

I've been receiving "Invalid sample detected, skipping.". When I remove this validation, I can see that CO2 is zero, but temperature and humidty readings are fine. What could be?

![image](https://github.com/Sensirion/arduino-i2c-scd4x/assets/55039179/8209b41b-985e-416c-ac6e-21b8349e69d2)

**Comment by antonio-emilio** [comment]
Also, performing the self test didn't returned anything. The returned value is 0.

**Comment by qfisch** [comment]
Hello @antonio-emilio ,

Interesting issue you have here.
Did you modify the example script outside of removing the validation ?
Do you have any other sensor on your custom board ?

**Comment by antonio-emilio** [comment]
> Hello @antonio-emilio ,
> 
> Interesting issue you have here. Did you modify the example script outside of removing the validation ? Do you have any other sensor on your custom board ?

Actually, I managed to make it work.... turns out that I didn't solder the sensor very great... Power issue :P
But thank you a lot!
