### ISSUE TITLE
Undocumented sleep mode and powerDown() / wakeUp() command codes

### ISSUE THREAD

**Issue by DominikHoen** [Sensirion/arduino-i2c-scd4x#7]
Hello dear all,

in the library, there are the powerDown() and wakeUp() functions, which send the command codes 0x36E0 and 0x36F6 respectively.
Also, the "sleep mode" is mentioned in the comments of these functions in SensirionI2CScd4x.h https://github.com/Sensirion/arduino-i2c-scd4x/blob/59aaa4d9ce9eae00865f398c31e2a38f0832d81e/src/SensirionI2CScd4x.h#L380.

My problem is that neither these commands, nor their codes nor the sleep mode are mentioned at all in the latest SCD4x datasheet (Version 1.1).
I've attached the Datasheet's Command Overview:
![image](https://user-images.githubusercontent.com/94743399/142724723-8bb93a01-20a2-48ae-a916-f653bbc4a854.png)

As you can see, they are missing.

My question is whether these commands work as described in the comments or if there's a reason they are not included in the Datasheet and whether it's safe to use these two functions.

Thanks in advance.

**Comment by MBjoern** [comment]
Dear @DominikHoen 

Powering down the sensor between single shots will likely result in increased signal noise and might compromise sensor accuracy. Also, power-cycling the sensor is not compatible with the automatic self-calibration algorithm that ensures highest long-term stability.

I hope this helps to answer your questions.

Best regards
